from config import config

# This file is required by the Matrix Portal library to properly initialize the board's WiFi chip.
#
# Do not edit this file.
# 
# Edit the 'confg' file instead.
#
secrets = {
    'ssid': config['wifi_ssid'],
    'password': config['wifi_password']
}
